/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro;

import Model.Dao.Insert_Into;
import Model.Curso;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 * 
 */
public class CadasCurso extends javax.swing.JFrame {

    /**
     * Creates new form CadasCurso
     */
    public CadasCurso() {
        initComponents();
        DefaultTableModel modelo =(DefaultTableModel) Table.getModel();
        modelo.setNumRows(0);
        Table.setRowSorter(new TableRowSorter(modelo));
        readCadasCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void readCadasCurso(){
       DefaultTableModel modelo =(DefaultTableModel) Table.getModel();
       modelo.setNumRows(0);
       Insert_Into I = new  Insert_Into();
       for(Curso d: I.readC()){
           
           modelo.addRow(new Object[]{
           
               d.getCodCursoc(),
               d.getNomeCurso(),
               d.getTipoCurso(),
               d.getCargaHoraria(),
               d.getCodinstituto(),
               
               
               
               
           
           });
       }
    
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cursos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CodCurso = new javax.swing.JLabel();
        CodCursoT = new javax.swing.JTextField();
        List = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListT = new javax.swing.JList<>();
        CargaHorária = new javax.swing.JLabel();
        CargaHoráriaT = new javax.swing.JTextField();
        CodInst = new javax.swing.JLabel();
        CodInstT = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        C = new javax.swing.JTextField();
        Titulo_jLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Bacharelado_jCheckBox = new javax.swing.JRadioButton();
        Especialista_jCheckBox = new javax.swing.JRadioButton();
        Mestrado_jCheckBox = new javax.swing.JRadioButton();
        Doutorado_jCheckBox = new javax.swing.JRadioButton();
        Atualizar = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cursos.setText("Cursos");

        CodCurso.setText("Código do Curso:");

        CodCursoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodCursoTActionPerformed(evt);
            }
        });

        List.setText("Nome do Curso:");

        ListT.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ciência da computação", "Administração de Empresas", "BioMedicina", "Ciências Biológicas", "Direito Educação Física", "Farmacologia", "Rede de Computadores", "Sistemas de Informações" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListT);

        CargaHorária.setText("Carga Horária:");

        CodInst.setText("Código do Instituto:");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        C.setEditable(false);

        Titulo_jLabel.setText("Tipo do curso:");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CodCursoc", "Nomecurso", "Tipocurso", "CargaHorária", "Codinstituto"
            }
        ));
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        Bacharelado_jCheckBox.setText("Bacharelado");
        Bacharelado_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bacharelado_jCheckBoxActionPerformed(evt);
            }
        });

        Especialista_jCheckBox.setText("Especialista");
        Especialista_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Especialista_jCheckBoxActionPerformed(evt);
            }
        });

        Mestrado_jCheckBox.setText("Mestrado");
        Mestrado_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mestrado_jCheckBoxActionPerformed(evt);
            }
        });

        Doutorado_jCheckBox.setText("Doutorado");
        Doutorado_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doutorado_jCheckBoxActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        Delete.setText("Deletar");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cursos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titulo_jLabel)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bacharelado_jCheckBox)
                                    .addComponent(Mestrado_jCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Especialista_jCheckBox)
                                    .addComponent(Doutorado_jCheckBox)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodCursoT, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CargaHorária)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CargaHoráriaT, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Voltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Atualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(List)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(C)
                                            .addComponent(jScrollPane1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CodInst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CodInstT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cadastrar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cursos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(List)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CodCurso)
                                .addComponent(CodCursoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Titulo_jLabel)
                                    .addComponent(Bacharelado_jCheckBox)
                                    .addComponent(Especialista_jCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mestrado_jCheckBox)
                                    .addComponent(Doutorado_jCheckBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CodInst)
                                    .addComponent(CodInstT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Delete)
                                .addGap(17, 17, 17)
                                .addComponent(Cadastrar)
                                .addGap(33, 33, 33))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CargaHorária)
                            .addComponent(CargaHoráriaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Voltar)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodCursoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodCursoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodCursoTActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        Curso d= new Curso();
        Insert_Into I =new  Insert_Into();
        d.setCodCursoc(Integer.parseInt(CodCursoT.getText()));
        String L=ListT.getSelectedValuesList().toString();
        C.setText(L);
        d.setNomeCurso(C.getText());
        
        d.setCargaHoraria(Float.parseFloat(CargaHoráriaT.getText()));
        d.setCodinstituto(Integer.parseInt(CodInstT.getText()));
        if(Bacharelado_jCheckBox.isSelected()){
           d.setTipoCurso(Bacharelado_jCheckBox.getText());
           }
        else if(Especialista_jCheckBox.isSelected()){
           d.setTipoCurso(Especialista_jCheckBox.getText());
           }
        else if(Mestrado_jCheckBox.isSelected()){
           d.setTipoCurso(Mestrado_jCheckBox.getText());
           }
        else if(Doutorado_jCheckBox.isSelected()){
           d.setTipoCurso(Doutorado_jCheckBox.getText());
           }
        
        
        

        I.create(d);
        readCadasCurso();
        
        
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Bacharelado_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bacharelado_jCheckBoxActionPerformed
        // TODO add your handling code here:
        Especialista_jCheckBox.setSelected(false);
        Mestrado_jCheckBox.setSelected(false);
        Doutorado_jCheckBox.setSelected(false);
    }//GEN-LAST:event_Bacharelado_jCheckBoxActionPerformed

    private void Especialista_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Especialista_jCheckBoxActionPerformed
        // TODO add your handling code here:
        Bacharelado_jCheckBox.setSelected(false);
        Mestrado_jCheckBox.setSelected(false);
        Doutorado_jCheckBox.setSelected(false);
    }//GEN-LAST:event_Especialista_jCheckBoxActionPerformed

    private void Mestrado_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mestrado_jCheckBoxActionPerformed
        // TODO add your handling code here:
        Bacharelado_jCheckBox.setSelected(false);
        Especialista_jCheckBox.setSelected(false);
        Doutorado_jCheckBox.setSelected(false);
    }//GEN-LAST:event_Mestrado_jCheckBoxActionPerformed

    private void Doutorado_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doutorado_jCheckBoxActionPerformed
        // TODO add your handling code here:
        Bacharelado_jCheckBox.setSelected(false);
        Especialista_jCheckBox.setSelected(false);
        Mestrado_jCheckBox.setSelected(false);
    }//GEN-LAST:event_Doutorado_jCheckBoxActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        // TODO add your handling code here:
        
         Curso d= new Curso();
        Insert_Into I =new  Insert_Into();
        d.setCodCursoc(Integer.parseInt(CodCursoT.getText()));
        String L=ListT.getSelectedValuesList().toString();
        C.setText(L);
        d.setNomeCurso(C.getText());
        
        d.setCargaHoraria(Float.parseFloat(CargaHoráriaT.getText()));
        d.setCodinstituto(Integer.parseInt(CodInstT.getText()));
        if(Bacharelado_jCheckBox.isSelected()){
           d.setTipoCurso(Bacharelado_jCheckBox.getText());
           }
        else if(Especialista_jCheckBox.isSelected()){
           d.setTipoCurso(Especialista_jCheckBox.getText());
           }
        else if(Mestrado_jCheckBox.isSelected()){
           d.setTipoCurso(Mestrado_jCheckBox.getText());
           }
        else if(Doutorado_jCheckBox.isSelected()){
           d.setTipoCurso(Doutorado_jCheckBox.getText());
           }
        
        
        

        I.Update(d);
        readCadasCurso();
        
    }//GEN-LAST:event_AtualizarActionPerformed

    private void TableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyReleased
        // TODO add your handling code here:
     CodCursoT.setText(Table.getValueAt(Table.getSelectedRow(),0).toString());
     C.setText(Table.getValueAt(Table.getSelectedRow(),1).toString());
     CargaHoráriaT.setText(Table.getValueAt(Table.getSelectedRow(),3).toString());
     CodInstT.setText(Table.getValueAt(Table.getSelectedRow(),4).toString());
    }//GEN-LAST:event_TableKeyReleased

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        Curso d= new Curso();
        Insert_Into I =new  Insert_Into();
        d.setCodCursoc(Integer.parseInt(CodCursoT.getText()));
        
        
        
        

        I.Delete(d);
        readCadasCurso();
        
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadasCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadasCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadasCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadasCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadasCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JRadioButton Bacharelado_jCheckBox;
    private javax.swing.JTextField C;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel CargaHorária;
    private javax.swing.JTextField CargaHoráriaT;
    private javax.swing.JLabel CodCurso;
    private javax.swing.JTextField CodCursoT;
    private javax.swing.JLabel CodInst;
    private javax.swing.JTextField CodInstT;
    private javax.swing.JLabel Cursos;
    private javax.swing.JButton Delete;
    private javax.swing.JRadioButton Doutorado_jCheckBox;
    private javax.swing.JRadioButton Especialista_jCheckBox;
    private javax.swing.JLabel List;
    private javax.swing.JList<String> ListT;
    private javax.swing.JRadioButton Mestrado_jCheckBox;
    private javax.swing.JTable Table;
    private javax.swing.JLabel Titulo_jLabel;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
